### ISSUE TITLE
explicitly add `URI(s)` section under  `STEP 7 - Post Deployment` section in Cloudmos Deploy doc

### ISSUE THREAD

**Issue by ghost** [akash-network/website#124]
We need to explicitly add `URI(S)` example somewhere under  `STEP 7 - Post Deployment` in https://akash.network/docs/deployments/cloudmos-deploy/ documentation.

As new users aren't aware about the application ports being exposed via such.

![image](https://github.com/akash-network/website/assets/107317698/f8eceef0-8bdb-4608-99f2-25fb99b78243)

**Comment by hiroyukikumazawa** [comment]
Has this issue been solved already?

**Comment by ghost** [comment]
> Has this issue been solved already?

It was not.

**Comment by hiroyukikumazawa** [comment]
> > Has this issue been solved already?
> 
> It was not.

What do you mean?

**Comment by hiroyukikumazawa** [comment]
sent pr - https://github.com/akash-network/website/pull/195
