### ISSUE TITLE
`GPU Resource Enablement` page should contain directions to `Provider Feature Discovery - GPU Configuration Integration Guide` & `Akash Provider Feature Discovery Upgrade/Enablement` pages

### ISSUE THREAD

**Issue by ghost** [akash-network/website#139]
Page https://akash.network/docs/providers/build-a-cloud-provider/gpu-resource-enablement/ should contain some link/info about these two pages, critical for enabling GPU support:
- https://akash.network/docs/providers/provider-feature-discovery-gpu-configuration-integration-guide/
- https://akash.network/docs/providers/akash-provider-feature-discovery-upgrade-enablement/

As new providers may find their provider does not detect the GPU because it is not in the https://github.com/akash-network/provider-configs/blob/main/devices/pcie/gpus.json file and they have to run the following command in order to update the gpus.json file:
```
provider-services tools psutil list gpu | jq '.cards[] | .pci | {vendor: .vendor, product: .product}'
```

Also, this page https://akash.network/docs/providers/akash-provider-feature-discovery-upgrade-enablement/#akash-provider-upgrade does not reflect all the attributes necessary, e.g.:
```
  - key: capabilities/gpu/vendor/nvidia/model/a100
    value: true
  - key: capabilities/gpu/vendor/nvidia/model/a100/ram/80Gi
    value: true
  - key: capabilities/gpu/vendor/nvidia/model/a100/ram/80Gi/interface/pcie
    value: true
  - key: capabilities/gpu/vendor/nvidia/model/a100/interface/pcie
    value: true
```

**Comment by HoomanDgtl** [comment]
this is resolved now

**Comment by HoomanDgtl** [comment]
@brewsterdrinkwater @chainzero : plzz close this issue. thanks
