### ISSUE TITLE
Replace the "ComfyUI" tile with "Ray cluster on Akash"

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#141]
On the homepage, we should replace the "ComfyUI" tile with "Ray cluster on Akash"

![image](https://github.com/akash-network/website/assets/116030971/fad63896-65a1-433e-8d09-6a44b6dccd69)

Title: Ray cluster on Akash
subheadline: This post explores the difficulties of parallelizing and scaling AI/ML workloads. We present Ray, a leading open-source framework (used by top ML teams) for large-scale parallel computing and distributed training.

graphic: 
![raycluster-akash-graphic](https://github.com/akash-network/website/assets/116030971/b32d9167-e28e-4f78-9b78-81f4e4514b26)

link to:  https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/

cc @anilmurty

**Comment by anilmurty** [comment]
Thanks @aktdenis - here are my suggestions:
Graphic: would add "Ray" somewhere (next to the ray logo inside its square box to the right of the logo would probably work)
Title: Ray clusters on Akash (note: plural for clusters)
Subheadline: Ray is the leading open-source framework for distributed machine learning. Explore how you can easily run Ray clusters on Akash Network in this post.

**Comment by aktdenis** [comment]
Thank you @anilmurty 

@HoomanHQ could you please take care of this and replace Comfy UI tile (on homepage) with:

Title: Ray clusters on Akash
Subheadline: Ray is the leading open-source framework for distributed machine learning. Explore how you can easily run Ray clusters on Akash Network in this post.
Link to: https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/

Graphic:
![ray-akash-graphic](https://github.com/akash-network/website/assets/116030971/9945c006-6141-44dd-ada8-734f36a8b779)

Feel free to close the issue when done. Much appreciated
