### ISSUE TITLE
Improve UX around linking

### ISSUE THREAD

**Issue by tgrecojs** [akash-network/website#153]
This issue is for updating the user experience surrounding this issue intends to provide an improved UX regarding navigation of the documentation. 

You can get a full understanding of this problem by checking out the video below. 

The TLDR: clicking on a section in the sidebar users should automatically bring the user to the first page within that section.

https://github.com/akash-network/website/assets/6646552/386cce07-3d21-40ee-b86c-a259ad5566a4

**Comment by tgrecojs** [comment]
updated this so that it covers the entire scope of the issue as discussed in today's meeting.

cc @HoomanHQ @brewsterdrinkwater

**Comment by hiroyukikumazawa** [comment]
Fixed this issue in https://github.com/akash-network/website/pull/157
We can test here - [Akash docs](http://65.109.84.205:4321/docs/)
Please check it out.

**Comment by ghost** [comment]
PR https://github.com/akash-network/website/pull/157 LGTM for the issue #152 

@tgrecojs please lmk if this PR looks good to you too so I can merge it.

**Comment by tgrecojs** [comment]
This looks great! Nice job @hiroyukikumazawa 

I'm not sure if this is something special with my computer, but I am finding that from time-to-time clicking on a sidebar triggers that section to toggle but the transition doesn't occur.

I don't think this is a blocker to merge as we can improve if someone else notices this behavior - just wanted to make note. nice job again! 

cc @andy108369

**Comment by hiroyukikumazawa** [comment]
Sent a PR - https://github.com/akash-network/website/pull/160

**Comment by hiroyukikumazawa** [comment]
sent pr again - https://github.com/akash-network/website/pull/196
