### ISSUE TITLE
Creating meaningful seperation / integration of users docs X engineering docs 

### ISSUE THREAD

**Issue by tgrecojs** [akash-network/website#156]
## Overview
Currently, the documentation is laid out in such a way that there are 2 distinct sections: "engineering docs" and "user docs" the engineering docs.

Engineering docs holds documentation for people who are working closer to the internals of the system should refer to. Inside users docs you'll find a information that caters to a wide audience ranging from individuals who are non-technical, to individuals who are technical to the point that they also frequent the "engineering docs" sections.

Below as a screenshot of showing how these sections are separated.

![ss_04232024_000310](https://github.com/akash-network/website/assets/6646552/6adb60f5-e478-4707-a6ea-3823c0abd19f)

You can view this for yourself by visiting [akash.network/docs](https://akash.network/docs). 

## Goal

This issue is intended to be an area for discussing and ultimately coming to an agreed upon layout for how this should be structured so that non-technical users aren't forced to sift through content that is foreign to them and similiarly, technical users can easily navigate through the sections of the docs without having to navigate past "cloudmos deploy" sections (for example)

**Comment by hiroyukikumazawa** [comment]
Who is solving this issue or not?

**Comment by tgrecojs** [comment]
This issue is meant to be an open forum for discussing possible solutions to the questions. If you have any suggestions on how it should be laid out, then go right ahead. @hiroyukikumazawa 


I actually do have some input on this matter, but I haven't had the time to focus on gathering the material necessary to provide a clear, coherent comment.
