### ISSUE TITLE
Re-organizing the two main network provider pages

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website#16]
Currently, we have two pages on the site that give an overview of Akash's active providers:
- https://akash.network/ecosystem/providers/
- https://akash.network/about/providers/

I would suggest that we organize these pages into a single `Providers` page that could live either in the `Network` dropdown in the main nav, or as a standalone nav item. Both of these pages give prospective (and current) Akash users a sense of the network scale and currently available resources, as well as a detailed look at current providers (including audit status, available resources, and uptime).

<img width="300" alt="Screenshot 2024-02-07 at 3 01 38 PM" src="https://github.com/akash-network/website-revamp/assets/24351900/bebf0f6e-2db7-4ad4-b139-db13ae1a24da">
<img width="300" alt="Screenshot 2024-02-07 at 2 53 03 PM" src="https://github.com/akash-network/website-revamp/assets/24351900/904e42c9-ed25-42b2-8788-4141e9d691a0">

**Comment by aktdenis** [comment]
thank you @zachhorn, 

as we already talked i do agree with this direction. 

i've prepared a draft here:

![about-akash-providers](https://github.com/akash-network/website-revamp/assets/116030971/8c97cebc-1570-4b15-bee0-df7195200019)

along with unified page for providers i've added two CTAs below vertical nav on the left side. 

users could reach this page through the main menu; network / dropdown / providers

<img width="207" alt="Screenshot 2024-02-22 at 10 03 35" src="https://github.com/akash-network/website-revamp/assets/116030971/05e4c5ad-05f2-42d4-9e88-ab548a391d2c">

important to note: if we proceed with this direction, we should remove the network capacity from the page; about / providers.

**Comment by ArthurEmma2** [comment]
@aktdenis Is the design finalized? I would like to work on this issue.

**Comment by aktdenis** [comment]
hey @ArthurEmma2 thank you! unfortunately, not yet. we still need to discuss it in our next wg-website meet.

**Comment by aktdenis** [comment]
> I recommend either separating the first and second sections with buttons on the left sidebar. This is because we have numerous provider cards, and placing next/prev buttons in the middle of the page may appear unprofessional.
> 
> Alternatively, we could arrange the second section at the top and the first section below. In this way, we can position the next/prev buttons at the end.

yup agree on this one. i would also implement additional menu option for providers as seen here;
![image](https://github.com/akash-network/website/assets/116030971/e443535e-ad19-46e7-97f5-2319eb8b2932)
this issue here: https://github.com/akash-network/website/issues/34

and this would live on akash.network/providers

mockup:
<img width="2347" alt="Screenshot 2024-05-21 at 15 44 24" src="https://github.com/akash-network/website/assets/116030971/9e329075-c2d1-4008-bf10-516afd6b2d62">

@HoomanHQ any thoughts on this one?

**Comment by aktdenis** [comment]
Sharing the latest "Providers" page. 

With this approach, I would suggest we remove the "Providers" from the "Ecosystem" page. 

@HoomanDgtl agreed to work on this issue in today's wg-meet. 

<img width="1427" alt="Screenshot 2024-08-22 at 16 24 38" src="https://github.com/user-attachments/assets/067db17c-6825-4d21-9968-d4568f3406bb">

**Comment by HoomanDgtl** [comment]
this is resolved
