### ISSUE TITLE
docs: improve accessibility of visualizations in engineering docs

### ISSUE THREAD

**Issue by tgrecojs** [akash-network/website#173]
While viewing the pages on an ipad i found myself unable to read the text inside the diagram shown within the engineering doc's [provider service](https://akash.network/docs/akash-provider-service-and-associated-sub-services/overview/) page.

Click the link above or navigate to: engineering docs > Akash Provider Operators > Provider Service and you'll see the view shown in the image below. 

![akash-visualization](https://github.com/akash-network/website/assets/6646552/4e8e9dc8-cfe5-4de4-9043-f7bfd8c33618)

feedback from others would be great as i'd like to ensure i'm not the only one who finds the text on the image difficult to read. there are tools for doing such analysis but not sure of them off the top of my head and would need to do some research. 

i think modifying the images all together would be ideal but i am not sure what the timeline would be for something like that. @HoomanHQ what are your thoughts on implementing a modal, or some feature would would make it easy or users to see a zoomed-in version of the image? if we had that, then we could use it whenever images like the one above appear. Notes: **this isn't the only instance where this occurs** (look around engineering docs)

**Comment by tgrecojs** [comment]
Below is a screenshot from graphics i found on the [general information page](https://akash.network/about/general-information/). 

![ss_04272024_000316](https://github.com/akash-network/website/assets/6646552/4274a9fd-3fd3-485b-8a5f-932989aa17b1)

I feel as though updating the current graphics to make use of this color scheme would seemingly fix the issue. If we needed zoom functionality as well, then that's no problem, but I think that it would be beneficial to the network if these visualizations were modified to look like the one on that page i've linked to. In addition to being more accessible, i think it looks much more professional (for lack of a better term).

@brewsterdrinkwater what level of effort would it take to get such changes made to these images in the docs? i'm not sure of the total number of images that need updating but i don't think it'd be > 4-5.

**Comment by hiroyukikumazawa** [comment]
I will solve this

**Comment by hiroyukikumazawa** [comment]
https://drive.google.com/file/d/1yjg5E8xwgk1QBkQL-rVF2y5UKpJk1YbJ/view?usp=sharing
We can drop each frame as svg or image and integrate to our website.
How about this approach? @HoomanHQ 

![image](https://github.com/akash-network/website/assets/142436034/4f83b482-ffeb-4af1-9be5-937df631b635)

**Comment by hiroyukikumazawa** [comment]
![akash drawio](https://github.com/akash-network/website/assets/142436034/c1d4e543-447c-4fd1-8d3f-8ee7032ea52b)
![akash drawio (1)](https://github.com/akash-network/website/assets/142436034/0ec6cfb3-e078-446a-bd52-6c8e45c1e6b0)
![akash drawio (2)](https://github.com/akash-network/website/assets/142436034/0b00cbcb-f6ac-479c-b217-b1501a968244)
![akash drawio (3)](https://github.com/akash-network/website/assets/142436034/3d86f364-0910-4eba-8b4d-a3b28260753d)
![akash drawio (4)](https://github.com/akash-network/website/assets/142436034/c593e8d9-983f-4339-b9f1-08ec9374be27)

**Comment by hiroyukikumazawa** [comment]
How is it going?

**Comment by HoomanDigital** [comment]
@hiroyukikumazawa are you working on this issue still? we just need to update few graphics in engineering docs as suggested in this issue..

The graphics you have created seems gtg, you can consider doing the same for others.

Thank you

**Comment by hiroyukikumazawa** [comment]
This is the draft of above image.
https://drive.google.com/file/d/1yjg5E8xwgk1QBkQL-rVF2y5UKpJk1YbJ/view?usp=sharing

**Comment by HoomanDigital** [comment]
here are the new refined images for eng-docs: https://drive.google.com/drive/folders/1ZJQvVFhMsua9E5zgSLiyHCMMJ5rR_NRd?usp=sharing

cc @hiroyukikumazawa

**Comment by HoomanDigital** [comment]
resolved
