### ISSUE TITLE
Getting Started section reorg

### ISSUE THREAD

**Issue by tgrecojs** [akash-network/website#179]
The Getting Started section is in need of an overhaul and so in this issue I've included screenshot of the getting started section with some proposed changes. I apologize in advance if it looks a bit cluttered! Please read into each section below to get a better understanding of what i'm proposing and also please comment below your thoughts.

![ss_04282024_000317](https://github.com/akash-network/website/assets/6646552/3e1e431d-9464-471e-80f5-06bb4f9de2bb)

Summary of proposed changes

### 1. Intro to Akash Section
I think the "Getting Started" does a great job of appealing to a wide audience. Both groups of people, technical and non-technical, can read through it and get the information they need to continue moving forward with making use of the network. That said, it's essentially a FAQ page so if this #76 is still something we're interested in, then I'm curious to here peoples thoughts on transforming this section into the FAQ page.

### 2. Consolidate Providers, RPC Nodes, and Validators section into one.
These sections are all fairly closely related. Taking this into account, along with the fact that each page contains a fairly small amount of text, I'm proposing that we merge all of these sections into one section, name TBD.

### 3. Move sections into "deployments category"
I don't think there is much benefit to having these pages baked into the first section of the docs. They actually contain some really useful information, however this information isn't what i would consider to be "entry level", which is why i'm proposing moving the OSEQ, DSEQ, GSEQ and SDL pages are best suited for the "deployments" section.

Also, there is currently a need for the "Akash CLI" section to be re-written, and I think this is an opportunity to supplement the new, useful guides present within that section

**Comment by Szu-Szu** [comment]
I like most of your suggestions here.  I'll have my own reorg map done fairly soon.  I will post here.

**Comment by HoomanDigital** [comment]
closing this issue.
