### ISSUE TITLE
Typo in https://akash.network/

### ISSUE THREAD

**Issue by hiroyukikumazawa** [akash-network/website#192]
![image](https://github.com/akash-network/website/assets/142436034/31527e1e-2fd8-4e7f-b69a-c8e10795fced)

**Comment by vatsal2809** [comment]
Hi, I have fix this issue and I am trying to push modified code to my local branch, but not able to do that. Can anyone help me ?

**Comment by hiroyukikumazawa** [comment]
You can fork this repository and send pr.
But before that, need to confirm this issue is suitable from team. @HoomanHQ

**Comment by hiroyukikumazawa** [comment]
And there isn't only one Preator typo here,
so hope to fix these all within one request

**Comment by vatsal2809** [comment]
Yes I have made multiple changes. But I cannot push the code in my local branch (issues/192) that I have created.

**Comment by hiroyukikumazawa** [comment]
> You can fork this repository and send pr. 

You can't push to this repo directly

**Comment by vatsal2809** [comment]
Okay, I got it and I have created PR as per guidelines.
