### ISSUE TITLE
[Docs] Page for How projects can Integrate into Akash Network (with relevant links to AkashJS)

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website#200]
There should be an easy to access page that shows teams how they can integrate their products and flows into Akash as easily as possible. 

There should be examples, links to the AkashJS and other relevant repos. 

This page should be easy to access from akash.network/docs, and it should be easily searchable

**Comment by hiroyukikumazawa** [comment]
Is there a figma design?

**Comment by hiroyukikumazawa** [comment]
If you provide me the contents, I will add

**Comment by aktdenis** [comment]
@brewsterdrinkwater could you please list. these relevant links to AkashJS? thanks 🙏

**Comment by aktdenis** [comment]
@HoomanDgtl please close this one. 
cc @brewsterdrinkwater
