### ISSUE TITLE
[Docs] Update Console documentation with new images. 

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website#207]
Console documentation is out of date. 

Please use console.akash.network to update the documentation with screen shots and proper steps for success.

**Comment by okhaimie-dev** [comment]
can you assign this task to me?

I am an Akash insider looking to get more involved with documentation

@brewsterdrinkwater

**Comment by okhaimie-dev** [comment]
@brewsterdrinkwater 

Is this the document you'd like me to replace
https://akash.network/docs/deployments/cloudmos-deploy/

Since Cloudmos is now Akash console

**Comment by fenilmodi00** [comment]
#233
slove this issue
