### ISSUE TITLE
make `chrony` a default/standard suggestion in the Akash provider build docs

### ISSUE THREAD

**Issue by ghost** [akash-network/website#243]
We should advertise `chrony` to be a standard in our Akash Docs

it's literally zero-config, just `apt -y install chrony` and it automatically works out of the box.. (as well as it automatically masks the `systemd-timesyncd` service after installed [via post scripts]).

## Rationale

We found some servers were out of sync, all attempts to fix `systemd-timesyncd` were not successful.
I also remember from my past job experience that `systemd-timesyncd` isn't ideal choice.

And we've been using `chrony` everywhere we could, it makes sure servers are in a perfect time sync.

**Comment by ghost** [comment]
Might as well want to give this hint (such as "install chrony") within these checks:

https://github.com/akash-network/helm-charts/blob/provider-11.0.2/charts/akash-provider/scripts/wait_for_rpc.sh#L30
https://github.com/akash-network/helm-charts/blob/provider-11.0.2/charts/akash-provider/scripts/wait_for_rpc.sh#L34
https://github.com/akash-network/helm-charts/blob/provider-11.0.2/charts/akash-provider/scripts/liveness_checks.sh#L32

**Comment by oiclid** [comment]
@andy108369 @brewsterdrinkwater I think I can take this. One question, though: what page should I add this on?

**Comment by HoomanDigital** [comment]
this is done #257 by @hiroyukikumazawa
