### ISSUE TITLE
docs: Praetor Apps Documentation needs to be created.

### ISSUE THREAD

**Issue by oiclid** [akash-network/website#247]
The Praetor App Documentation is missing from the Akash Documentation website. It needs to be created.  I would like to take on the task.

**Comment by brewsterdrinkwater** [comment]
The praetor process will be changing soon, as a part of the work for Console 2.0. The documentation will need to be changed at that point, but it could be beneficial to have some starting off docs right now. 

It would also be great to link to open source repos and talk about Praetor a bit at a high level.

**Comment by oiclid** [comment]
@brewsterdrinkwater I could start off by using the [docs](https://docs.praetorapp.com) on the Praetor site as a reference. I'd obviously try to follow the steps so as to make sure it is currently accurate.

**Comment by oiclid** [comment]
@brewsterdrinkwater Here's the PR for this: https://github.com/akash-network/website/pull/285
