### ISSUE TITLE
Update the Events page

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website#250]
We need to update the [Events Page](https://akash.network/community/events/) to reflect all new events through the end of the year.

We should also consider how to surface this page more actively. Currently, it's `Home > Community > Events`. Can we make this page easier for new users to find?

cc @aktdenis @vakaytion

<img width="2248" alt="Screenshot 2024-06-14 at 3 04 31 PM" src="https://github.com/akash-network/website/assets/24351900/699deab6-776b-4d24-991f-76c8ec79379c">

**Comment by hiroyukikumazawa** [comment]
@zachhorn, How about having a dropdown like Network tab?
![image](https://github.com/akash-network/website/assets/142436034/c1efdf29-4348-4359-885d-a841aef375d8)

**Comment by hiroyukikumazawa** [comment]
Or a new Events tab?
![image](https://github.com/akash-network/website/assets/142436034/89239c57-63d8-410f-8733-54f8d5e530d0)

**Comment by aktdenis** [comment]
thanks @hiroyukikumazawa, since there are several issues to resurface some of the pages on the website - we need to rethink the whole menu experience. i'll provide a draft and combine concerned issues into one

**Comment by hiroyukikumazawa** [comment]
Ok, thank you.

**Comment by hiroyukikumazawa** [comment]
@aktdenis if you decided, please let me know.

**Comment by aktdenis** [comment]
@HoomanDgtl please close this issue
