### ISSUE TITLE
Improve - Pricing page - visibility and experience

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#252]
we should bring the pricing section closer to the users (website visitors).

there are several ways to achieve this.
first, bringing additional menu item "pricing" to the main menu (combining menu item w GPU pricing)
second, highlighting pricing item in the main menu (see attachment below)
third, on the pricing page we introduce a switch, for users to be able to switch between pricing calculator (and comparison) and gpu price list. this way we bring scattered information to one single page. 

** i suggest we slightly redesign the resources calculator and create a slider option. it's easier and faster to tweak the numbers and too see the estimate + comparison. 

<img width="1550" alt="Screenshot 2024-06-17 at 14 48 45" src="https://github.com/akash-network/website/assets/116030971/0c3a1bfa-9d9a-46da-9ac0-a0f72e2c8ef6">

next to the items above i suggest creating an additional section to highlight USPs - these can be pulled out from this text: 
Akash employs a unique “Reverse Auction” system. Network deployers specify the preferred price for their desired resources, and providers compete to fulfill the request. This approach consistently yields substantially lower costs and greater choice while maintaining self-sovereign control. Akash operates as an open-source, community-driven platform, powered by a L1 blockchain and the AKT utility token.

we're pulling relevant information and presenting it in smaller chunks, making it easier for users to consume this info.

<img width="1007" alt="Screenshot 2024-06-17 at 14 49 02" src="https://github.com/akash-network/website/assets/116030971/c6af2570-7ca8-4701-94ac-e2005ff04acc">

feedback and suggestions from the community are always welcome.

**Comment by HoomanDigital** [comment]
@aktdenis how are you imaging this in mobile screen for both cases?  pricing & gpu.. thanks

**Comment by aktdenis** [comment]
@HoomanDigital I'll provide a design draft for the mobile as well - as soon as we align on the direction of this page

**Comment by HoomanDigital** [comment]
thanks @aktdenis for the update..
@hiroyukikumazawa : as said, you can restart working on this issue once the direction is clear. Really appreciate the PR you created against this issue.

Thanks

**Comment by aktdenis** [comment]
i suggest we add "provider earn calculator" to the pricing page.

mockup:

<img width="1043" alt="Screenshot 2024-07-29 at 14 17 51" src="https://github.com/user-attachments/assets/53e4ee0a-cc0c-4c83-8507-84ed3e76d07e">

we would pull information from here: https://akash.praetorapp.com/calculator?_ga=2.248039621.312799023.1722255514-1075541791.1719239261&_gl=1*42bx9c*_ga*MTA3NTU0MTc5MS4xNzE5MjM5MjYx*_ga_0G158R2TYZ*MTcyMjI1NTUxNC42LjAuMTcyMjI1NTUxNC4wLjAuMA.. 

cc @jigar-arc10 @devalpatel67

**Comment by aktdenis** [comment]
Sharing all three pages for "pricing"

GPU Pricing / Usage Pricing Calculator / Provider Earn Calculator

<img width="1098" alt="Screenshot 2024-07-30 at 14 01 55" src="https://github.com/user-attachments/assets/2408aebd-00ca-41c0-9f99-31681bbadabd">

Any takers for this issue? 

cc @HoomanDigital @hiroyukikumazawa

**Comment by HoomanDigital** [comment]
This looks good. Let's wait to see if @hiroyukikumazawa is interested in taking this on; otherwise, we are open to taking it and completing it ourselves.

The only thing is, if Hiro takes this, we expect he has a thorough understanding of the Praetor API, as this is more of a technical implementation. @hiroyukikumazawa, please let us know if you are willing to take this on.

cc @aktdenis 

Thanks.

**Comment by hiroyukikumazawa** [comment]
I will take this. @HoomanDigital

**Comment by aktdenis** [comment]
An update on this issue. Figma was provided to @hiroyukikumazawa and he is working on implementation.

**Comment by gosuri** [comment]
LGTM!

**Comment by HoomanDgtl** [comment]
this is resolved
