### ISSUE TITLE
The `Deploy Now` button style is not good.

### ISSUE THREAD

**Issue by hiroyukikumazawa** [akash-network/website#253]
Here `Deploy Now` button style is not good.
https://akash.network/about/pricing/custom/
![image](https://github.com/akash-network/website/assets/142436034/466c1d76-c032-44fa-bdee-2e9ca213d175)

**Comment by hiroyukikumazawa** [comment]
Please check the pr https://github.com/akash-network/website/pull/254

**Comment by aktdenis** [comment]
@HoomanDigital if this one is fixed, please close it. thank you"
