### ISSUE TITLE
Sort feature is not working in GPU pricing page.

### ISSUE THREAD

**Issue by hiroyukikumazawa** [akash-network/website#255]
When GPUs have 0 availability device, the sort feature is not working.

https://github.com/akash-network/website/assets/142436034/73e48285-fc9e-4b67-9df9-c9d44381e627

**Comment by aktdenis** [comment]
thank you very much @hiroyukikumazawa , @HoomanDigital can you please have a look?

**Comment by aktdenis** [comment]
@HoomanDigital if this one is fixed, please close it. thank you"
