### ISSUE TITLE
Content updates on "Development" page

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#260]
There are couple of content related things we need to fix on the `Development` page. 

The second paragraph is talking about "Getting Acquainted" section, but that sections in no where to be found (it was probably on the previous website)

Let's replace it with:
The Akash Network community welcomes contributions from all skill levels. If you’re interested in contributing, visit our [project list](https://github.com/orgs/akash-network/projects) to find a project that matches your skillset.

<img width="1592" alt="Screenshot 2024-06-19 at 14 31 45" src="https://github.com/akash-network/website/assets/116030971/129e5019-0f63-4e25-b14e-b8a1d14ed40e">

This section is called Community groups but the copy is about SIGs. 

<img width="1257" alt="Screenshot 2024-06-19 at 14 30 22" src="https://github.com/akash-network/website/assets/116030971/5203f458-8b82-466b-81ac-d4b113556c7a">

Here is the content we had in the previous website:
The Akash Network is supported by a diverse group of users, contributors, and supporters. We strive to improve the project and work together efficiently. We’re proud of our progress over the years. All aspects of the Akash Network - from code to culture - are managed by the community and divided into three programs.

**Comment by hiroyukikumazawa** [comment]
Please check #268 @aktdenis @HoomanDigital
