### ISSUE TITLE
Add `Case Studies` page

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#261]
As we talked several times during wg-website, we agreed we should have a dedicated section on the Akash Network website to showcase various case studies. 

Possible case studies we could pull from blog:

[Foundation AI Model Training on Akash](https://akash.network/blog/foundation-ai-model-training-on-akash/)
[Passage Leverages Akash to Launch the First Virtual World on Permissionless GPUs](https://akash.network/blog/passage-leverages-akash-to-launch-the-first-virtual-world-on-permissionless-gpus/)
[Running vLLM on Akash](https://akash.network/blog/running-vllm-on-akash/)
[Brev.dev Leverages Akash Network's Permissionless GPU Infrastructure to Seamlessly Scale](https://akash.network/blog/brev-dev-leverages-akash-networks-permissionless-gpu-infrastructure-to-seamlessly-scale/)
[Distributed Machine Learning on Akash Network with Ray](https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/)
[Akash Network and Solve.Care Bring True Patient Data Ownership to the Healthcare Industry](https://akash.network/blog/akash-network-and-solve-care-bring-true-patient-data-ownership-to-the-healthcare-industry/)

This issue serves as a starting point for further discussion and refinement. 
Design draft will follow.

**Comment by hiroyukikumazawa** [comment]
Please let me know when the design darft is completed.

**Comment by HoomanDigital** [comment]
@hiroyukikumazawa lmk if you want to take on this, thank you

**Comment by hiroyukikumazawa** [comment]
> @hiroyukikumazawa lmk if you want to take on this, thank you

I will

**Comment by hiroyukikumazawa** [comment]
> As we talked several times during wg-website, we agreed we should have a dedicated section on the Akash Network website to showcase various case studies.
> 
> Possible case studies we could pull from blog:
> 
> [Foundation AI Model Training on Akash](https://akash.network/blog/foundation-ai-model-training-on-akash/) [Passage Leverages Akash to Launch the First Virtual World on Permissionless GPUs](https://akash.network/blog/passage-leverages-akash-to-launch-the-first-virtual-world-on-permissionless-gpus/) [Running vLLM on Akash](https://akash.network/blog/running-vllm-on-akash/) [Brev.dev Leverages Akash Network's Permissionless GPU Infrastructure to Seamlessly Scale](https://akash.network/blog/brev-dev-leverages-akash-networks-permissionless-gpu-infrastructure-to-seamlessly-scale/) [Distributed Machine Learning on Akash Network with Ray](https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/) [Akash Network and Solve.Care Bring True Patient Data Ownership to the Healthcare Industry](https://akash.network/blog/akash-network-and-solve-care-bring-true-patient-data-ownership-to-the-healthcare-industry/)
> 
> This issue serves as a starting point for further discussion and refinement. Design draft will follow.

Please provide me the design draft if ready.

**Comment by HoomanDigital** [comment]
@aktdenis can't we just highlight case-studies in form of blog on homepage similar to what we are doing with latest posts. We can define the tag for each blog..?

**Comment by aktdenis** [comment]
@HoomanDigital i'm thinking this should be a section of its own - possibly with a menu item. 

i would even use a different layout, so there is differentiation between blog and case studies posts. 
something in the form of;
- logo + project name (or case study headline)
- description
- cta
<img width="1087" alt="Screenshot 2024-06-24 at 10 09 07" src="https://github.com/akash-network/website/assets/116030971/421113f1-0722-423a-957d-51d557dcfbae">

we would need input from @zachhorn to see how this evolves.

**Comment by hiroyukikumazawa** [comment]
I will solve this issue.

**Comment by aktdenis** [comment]
here is a list of possible case studies:

https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/
https://akash.network/blog/akash-network-and-solve-care-bring-true-patient-data-ownership-to-the-healthcare-industry/
https://akash.network/blog/passage-leverages-akash-to-launch-the-first-virtual-world-on-permissionless-gpus/
https://akash.network/blog/brev-dev-leverages-akash-networks-permissionless-gpu-infrastructure-to-seamlessly-scale/
https://akash.network/blog/running-vllm-on-akash/
https://akash.network/blog/decentralized-ai-model-training-on-akash-with-flockio/
https://akash.network/blog/prime-intellect-integrates-permissionless-akash-gpus/

@zachhorn any thoughts on these?

**Comment by aktdenis** [comment]
Just thought of an easier and faster way to implement "case studies" - We add a new tag in the blog called "case studies". When we link to "case studies" we showcase only posts tagged with "case studies"

**Comment by HoomanDgtl** [comment]
this is resolved
