### ISSUE TITLE
Akash Docs / Section: Quickstart - Update cards layout and replace icons

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#264]
Akash Docs / Section: Quickstart

First two tiles should follow the width of the tiles below (3 column layout)

The first icons represents "exit". It should indicate "Console" and the second one "CLI". 

<img width="1950" alt="Screenshot 2024-06-20 at 15 27 25" src="https://github.com/akash-network/website/assets/116030971/b8eea7f7-e2f2-4611-a216-3c681b62d69f">

**Comment by HoomanDigital** [comment]
sure: we kept it that way to ensure it can cover the whole width. but will fix it..
