### ISSUE TITLE
Get Started / Deploy - Update content and links

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#265]
https://akash.network/deploy/

The content of these 3 tiles is outdated: I suggest we replace them with: https://akash.network/docs/getting-started/quickstart-guides/akash-console/

<img width="1667" alt="Screenshot 2024-06-20 at 15 38 54" src="https://github.com/akash-network/website/assets/116030971/0d1c57a5-da75-49de-8a34-790b257911bc">

The middle tile "Akash Console Documentation" has a dead-end. Please update the link to: https://akash.network/docs/deployments/akash-console/

<img width="1650" alt="Screenshot 2024-06-20 at 15 44 13" src="https://github.com/akash-network/website/assets/116030971/dfd0ca41-d39b-4110-b042-38c452a7d762">

While we're at the "Get Started" section, this icon is way to big and thick - please reduce the size. 
<img width="1619" alt="Screenshot 2024-06-20 at 15 41 01" src="https://github.com/akash-network/website/assets/116030971/ae390959-ecce-4fee-afbe-2e0204d18f1b">

**Comment by HoomanDigital** [comment]
sure..

**Comment by HoomanDigital** [comment]
done #271
