### ISSUE TITLE
GPU Pricing / Link each chipset through CTA "Rent now" to preselected GPU on Console

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#266]
On the GPU pricing page of the Akash Network website, there is a list of GPUs with a "Rent Now" call-to-action (CTA). When a user clicks on this CTA, it should redirect them to the Akash Console with the corresponding GPU preselected. 

<img width="1688" alt="Screenshot 2024-06-20 at 20 40 26" src="https://github.com/akash-network/website/assets/116030971/fc13a669-1b5d-43e7-8207-ef29ed6f3c2f">

Experience should be seamless and the selected GPU should be correctly highlighted on the Console. 

<img width="1710" alt="Screenshot 2024-06-20 at 20 40 59" src="https://github.com/akash-network/website/assets/116030971/087322f7-aacf-4021-8e38-f8fbd4823275">

With this approach we'll save some time for our users

**Comment by HoomanDigital** [comment]
great, is the functionality to do so on akash console live? As i remember, when we implemented this feature, the functionality was lacking to do so..

thanks

**Comment by aktdenis** [comment]
that's true, back then it was not available. i was talking to max a while ago, and he said this functionality is available.

**Comment by HoomanDigital** [comment]
great then: we will implement this soon..

**Comment by HoomanDigital** [comment]
done #271
