### ISSUE TITLE
docs: broken and out-of-date links

### ISSUE THREAD

**Issue by oiclid** [akash-network/website#274]
I realized there are quite a few broken links as well as links that connect to out-of-date content. I would like to go through the entire documentation and check on every single link to make sure they are working properly and point to up-to-date content. If not, I'll either redirect the broken links to the relevant pages, create appropriate pages for the content (where possible), or redirect the links to the current and existing content.

**Comment by aktdenis** [comment]
thank you @oiclid , would you mind creating a list of broken links?

**Comment by oiclid** [comment]
@aktdenis  Ok.

**Comment by oiclid** [comment]
@aktdenis Here's a living [spreadsheet](https://docs.google.com/spreadsheets/d/1g9rG9YtCvTOzo-F1sYWd10Mv6hMEhAjV5LEY6ylp2Q4/edit?usp=sharing). I found 40 broken links in the first 10-15% of the docs. I'll continue creating the list whenever I have free time this week. hoping to be done before the week ends.

**Comment by aktdenis** [comment]
@oiclid looking great! appreciate your effort 🙏🙏

**Comment by HoomanDigital** [comment]
this is resolved by @oiclid

**Comment by oiclid** [comment]
@brewsterdrinkwater Hi. Can you please reopen this issue? I made the final push earlier today.

**Comment by oiclid** [comment]
> @brewsterdrinkwater Hi. Can you please reopen this issue? I made the final push earlier today.

Actually, never mind. The work is done, just waiting for the most recent PR to be reviewed and merged.

**Comment by brewsterdrinkwater** [comment]
where is the PR @oiclid ?

**Comment by oiclid** [comment]
Sorry, here they are:
@brewsterdrinkwater 

https://github.com/akash-network/website/pull/304
https://github.com/akash-network/website/pull/315
https://github.com/akash-network/website/pull/308
