### ISSUE TITLE
Token / Buying AKT; Add Upbit 

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#278]
We need to add Upbit to `Buying AKT` section on the page [$AKT Token](https://akash.network/token/):

<img width="1172" alt="Screenshot 2024-06-25 at 11 43 38" src="https://github.com/akash-network/website/assets/116030971/4da57046-a751-4202-bd6b-edec3a1bf592">

Let's put it after Kraken for now.

**Comment by aktdenis** [comment]
Let's add Bitpanda as well. This one comes after RevolutApp.

**Comment by HoomanDigital** [comment]
resolved
