### ISSUE TITLE
Main Menu Nav / Redesign and introduction of Dropdown Menus

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#287]
### **Main Navigation Issue:**
The previous design of Akash website aimed for simplicity, making all pages accessible with a single click from the menu. As the website has grown and more pages have been added, this approach is no longer practical. To improve navigation and user experience, we need to introduce a menu with dropdown options.

### **Secondary Navigation Issue:**
The same issue arises with the secondary vertical navigation which appears on most pages. 
With this approach, users have to click through different pages just to find out what options are available under each section. Also, these menus are difficult to replicate in mobile view, leading to a clumsy user experience where users must make multiple choices to find what they're looking for. As we continue to add new pages and content, these navigation issues could become even more problematic.

- Desktop - vertical nav reference: 
<img width="397" alt="Screenshot 2024-06-25 at 16 38 59" src="https://github.com/akash-network/website/assets/116030971/332b4e70-472e-4f78-b5d7-d1592220f6bd">

- Mobile - vertical nav reference:
<img src="https://github.com/akash-network/website/assets/116030971/83f62baa-e967-4154-afd6-f889d9f7d1be)" width=400>

_Note: This navigation was part of the theme website used to had. The website had a revamp in the beginning of the year and is using Astro atm. So, we're no longer obliged to stick to this solution._

Mentioning a couple of issues that could benefit with a redesigned menu:

- Providers information is scattered / issue: https://github.com/akash-network/website/issues/16
- Pricing is hard to reach, GPUs availability could be connected to pricing / issue: https://github.com/akash-network/website/issues/252
- Events are hard to find / issue: https://github.com/akash-network/website/issues/250
Etc.
- And several other issues were brought up during wg-website meetings or IRL conversations

### **Solution: **
To keep the website's look and feel consistent, I suggest we use the same Tailwind library for designing "dropdown menus" or "flyout menus" as shown [here](https://tailwindui.com/components/marketing/elements/flyout-menus).

### **Design of the main menu navigation: **

- Network dropdown
addition of new items; case studies + integrations 
we communicate "Stats" on a secondary level as an indicator it's an external link (opens in new tab)
<img width="643" alt="Screenshot 2024-06-26 at 11 28 42" src="https://github.com/akash-network/website/assets/116030971/895798cb-8060-4589-bde4-303cfa313499">

- Development dropdown
we communicate "Product & Engineering Roadmap" on a secondary level as an indicator it's an external link (opens in new tab - github)

<img width="349" alt="Screenshot 2024-06-26 at 11 30 53" src="https://github.com/akash-network/website/assets/116030971/1f95922f-4696-4172-b5c0-ddcccfca9f36">

- Community dropdown
<img width="359" alt="Screenshot 2024-06-26 at 11 34 42" src="https://github.com/akash-network/website/assets/116030971/b69bef7f-643b-4864-8a97-1bad8ac83334">

- Ecosystem dropdown
<img width="489" alt="Screenshot 2024-06-26 at 11 36 16" src="https://github.com/akash-network/website/assets/116030971/1dbfcec5-5105-41ed-bb5e-c6d8681393c8">

- Design of the secondary menu navigation - this one is used when a user has already opened one of the pages with dropdown options. With this approach we're opening the doors for viewers to jump right at the content they might be looking for - without touching the dropdown menu again. 

<img width="1104" alt="Screenshot 2024-06-26 at 11 56 37" src="https://github.com/akash-network/website/assets/116030971/05424ffb-7cd4-41a9-b0da-54b1509c87d4">

- Secondary menu in the mobile view introduces much more intuitive experience (unlike the existing menu mentioned above)
<img width="267" alt="Screenshot 2024-06-26 at 11 57 08" src="https://github.com/akash-network/website/assets/116030971/8dea2c1f-58a5-4209-9ec4-531c00c2ca6b">

- Mobile menu with dropdown option
<img width="262" alt="Screenshot 2024-06-26 at 11 58 34" src="https://github.com/akash-network/website/assets/116030971/1a6667a6-fe8b-4d95-bbaf-43b9b3afb518">

This issue serves as a starting point for further discussion and refinement.

**Comment by HoomanDigital** [comment]
This is great starting point to address these issues, we are just little bit skeptical about secondary nav when we already have the options in dropdown.. Can we have some better approach in case of desktop to avoid secondary nav??

![image](https://github.com/akash-network/website/assets/172995301/c95da904-4f5c-4fe4-9c49-6b0b980eec56)

**Comment by aktdenis** [comment]
True. All items are available in the dropdown. But with this approach users don't have to get back to dropdown to reach any of the sub-pages. + I believe it works very well in the mobile view with the option to slide between secondary menu items

**Comment by ShinySyntax** [comment]
Hello, @aktdenis 
I will take this issue

**Comment by aktdenis** [comment]
hey @kindlyman343423 thanks for showing interest in this issue. personaly i would like to see @HoomanDigital take this issue since they've already worked on the existing menu. 

any other issue you would be interested?

**Comment by aktdenis** [comment]
@HoomanDigital would you be willing to take this issue please? thank you!

**Comment by HoomanDigital** [comment]
> @HoomanDigital would you be willing to take this issue please? thank you!

yes

**Comment by ShinySyntax** [comment]
> hey @kindlyman343423 thanks for showing interest in this issue. personaly i would like to see @HoomanDigital take this issue since they've already worked on the existing menu.
> 
> any other issue you would be interested?

Got it

**Comment by HoomanDgtl** [comment]
this is resolved
