### ISSUE TITLE
the Look & Feel

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#290]
We had several conversations with various core members about aligning Akash's positioning with the brand's look and feel.

Here are couple of things we discussed:

### **Switching from satoshi to Inter font.**
Looking to replace satoshi font with “Inter” - or any other “open-source helvetica”. 
<img width="800" alt="Screenshot 2024-06-27 at 11 46 04" src="https://github.com/akash-network/website/assets/116030971/bbb93c2a-cf15-4eab-8afb-52f289aca7ed">

Reasoning behind this is:
It fits Akash as a brand and the way it’s positioned now in the cloud/gpu world. Inter for example is perfect for user interfaces because readability, forming hierarchy, is widely recognized by users and designers. It brings a level of professionalism and a sense of reliability. Many UI libraries are using the Inter font, which highlights its effectiveness and popularity.

### **Introducing a serif for headlines + branding** 

Reasoning behind this is: In a market where many tech and web3 brands use bland fonts, a serif font helps a brand stand out and create a unique identity. It brings a level of heritage, it blends tradition and modernity - making it look innovative and trustworthy. Serif fonts help build a sophisticated brand image, associated with high-end and credibility.  
Introducing a/acc style of imagery across all branding touchpoints. 

Important to note; just like "inter" we are mentioning above - the serif font should be opensourced as well.

Example using "Instrument Serif": 
<img width="844" alt="Screenshot 2024-06-27 at 11 53 16" src="https://github.com/akash-network/website/assets/116030971/839be15f-088d-4d7b-807f-0e15ac9b51d6">

Example using "Libre Condensed"
<img width="845" alt="Screenshot 2024-06-27 at 11 55 13" src="https://github.com/akash-network/website/assets/116030971/c0891fed-18e1-4c15-b10e-86c5aaf4b3fe">

### **AI imagery**
Incorporating AI-generated imagery is a valuable use case for Akash because it showcases how a GPU marketplace platform efficiently creates branding assets while using AI technology. On the other hand, it speeds up production, providing flexibility and allowing anyone to follow a set of guidelines to consistently produce Akash branded imagery. But first, we have to define the "Akash style" ensuring these visuals stand out distinctly from other brands.

We've explore this direction [here](https://akash.network/blog/a-acc-akash-accelerationism/):
![image](https://github.com/akash-network/website/assets/116030971/25e8170a-8979-43a6-b4d3-85c66802bc7b)

**### UI components**
Use [Shadcn UI components](https://ui.shadcn.com/) across all touchpoints
To ensure all Akash touchpoints are consistent, we need to standardize use of the Shadcn UI library for all current and future projects. This includes adapting our past projects as well. Next to having a consistent look and feel across different touchpoints there are other benefits, such as; efficiency, maintainability, scalability, reducing learning curve for new contributors etc. 

When final decisions are made we need to think about updating Akash brand manual with newly defined brand components.

This issue serves as a starting point for further discussion and refinement.

**Comment by hiroyukikumazawa** [comment]
I will solve this issue.

**Comment by HoomanDigital** [comment]
I like: Libre Condensed

**Comment by fenilmodi00** [comment]
Yaa, I totally agree with this! The recently launched [black-forest-labs/FLUX.1-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main) would be the best model for this purpose. It can also be fine-tuned to generate Akash-branded assets, perfectly aligning with the Akash style. This approach not only streamlines the process but also showcases the best use of AI for creating consistent and distinctive visual assets.

**Comment by aktdenis** [comment]
@HoomanDgtl please close this issue

**Comment by HoomanDgtl** [comment]
this issue is resolved.

thanks
