### ISSUE TITLE
persistent storage (Ceph): require 10GbE NIC cards

### ISSUE THREAD

**Issue by ghost** [akash-network/website#293]
We should update the docs to require 10GbE NIC cards for Ceph nodes.

![image](https://github.com/akash-network/website/assets/107317698/7b413bd2-635c-489b-a122-7bbf8cbe16a4)

Doc to update
https://akash.network/docs/providers/build-a-cloud-provider/helm-based-provider-persistent-storage-enablement/

**Comment by hiroyukikumazawa** [comment]
I will solve this issue.

**Comment by HoomanDigital** [comment]
this is resolved
