### ISSUE TITLE
Community - Events / Switch "upcoming" to default

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#294]
https://akash.network/community/events/upcoming/

@HoomanDigital Let's switch from showing "All" to "Upcoming" on community-events page. 

<img width="1180" alt="Screenshot 2024-06-27 at 20 38 00" src="https://github.com/akash-network/website/assets/116030971/71c76daa-0e7f-4abf-b154-d16df2b65a7a">

**Comment by HoomanDigital** [comment]
this is resolved now: @hiroyukikumazawa
