### ISSUE TITLE
suggestion: global search across whole website

### ISSUE THREAD

**Issue by HoomanDigital** [akash-network/website#299]
As the website grows, so does the amount of information. We suggest implementing a global search feature across the entire website, capable of performing high-quality searches on all content.

**Comment by hiroyukikumazawa** [comment]
good point, let me do this

**Comment by HoomanDigital** [comment]
@hiroyukikumazawa thanks for showing interest, lets wait for others to share feedback. this is under discussion..

**Comment by Tunki1201** [comment]
@HoomanDigital 
Is this still open?
If so, I will try with this ticket.

**Comment by HoomanDigital** [comment]
hey @Tunki1201 , this is still under discussion and open (not finalized yet)

**Comment by Tunki1201** [comment]
@HoomanDigital
thank you for your reply. I will try with this ticket.

**Comment by aktdenis** [comment]
@HoomanDgtl please expand this issue and share the details of implementation, functionality etc. so we can have a detailed discussion. ty!

**Comment by HoomanDgtl** [comment]
sure @aktdenis : will follow up on this with more details..  

thanks

**Comment by HoomanDgtl** [comment]
considering nav improvements, this doesn't make any sense
