### ISSUE TITLE
Add akash-chat-api to the Ecosystem page

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#316]
We need to add a tile for Akash Chat - API to the [Ecosystem page (showcase)](https://akash.network/ecosystem/showcase/latest/) and link to: https://chatapi.akash.network/

**Comment by aktdenis** [comment]
for the description text we can use the same as on chat API link; Akash Chat API, an open and permissionless Llama3 API powered by the Akash Supercloud that anyone can access at completely zero-cost. graphic: ![akash-chat-api](https://github.com/user-attachments/assets/5471bf6b-bb44-49fd-b193-12d0be063a22)

**Comment by aktdenis** [comment]
@hiroyukikumazawa would you be able to take this one? thanks

**Comment by hiroyukikumazawa** [comment]
Yes, I will take this

**Comment by aktdenis** [comment]
hey @hiroyukikumazawa, you need anything else for this issue?
