### ISSUE TITLE
Update the Events Page for all upcoming events on the Akash Calendar

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website#318]
Some events need to be added to the [Akash Network Events page](https://akash.network/community/events/upcoming/)

Core team to share dates for events.

**Comment by aktdenis** [comment]
head: Korea Blockchain Week 2024
link: https://koreablockchainweek.com/
date: Sep 1, 2024
descripiton: KBW is an annual global blockchain and Web3 festival held in Seoul, South Korea, since 2018.
