### ISSUE TITLE
Docs: update guides

### ISSUE THREAD

**Issue by oiclid** [akash-network/website#320]
Most of the content in the guides is at least two years old. I would like to create guides to be included in the documentation. I intend to focus on tools for AI/GPU, deployments, integrations, and dashboards.  I would use the Akash-as-tons, as well as technical material from the Akash blog, and interested teams in the Akash ecosystem. 

I would only be adding material about mature products/tools, and I am aiming for a minimum of 5 and a maximum of 10 additional guides.

**Comment by brewsterdrinkwater** [comment]
Can you use some recent examples from awesome Akash as well? This would be helpful.

**Comment by oiclid** [comment]
> Can you use some recent examples from awesome Akash as well? This would be helpful.

@brewsterdrinkwater Okay. Doing that may take me beyond the 10 I planned to do. Should I aim for 15 or 20 new guides?

**Comment by oiclid** [comment]
Done.

**Comment by oiclid** [comment]
@brewsterdrinkwater https://github.com/akash-network/website/pull/323
