### ISSUE TITLE
Update Akash Ecosystem page with the latest relevant projects

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#336]
We need to update this page with new projects:
https://akash.network/ecosystem/deployed-on-akash/latest/

This is how projects are added to the ecosystem:
https://github.com/akash-network/website?tab=readme-ov-file#how-to-contribute-a-project-to-the-ecosystem

Let's start by creating a list of projects in the comments below.

**Comment by aktdenis** [comment]
Let's move the "AI & ML" category to the top of the list, below "All".

**Comment by aktdenis** [comment]
When switching categories on "Deployed on Akash", order categories keep switching. 
It should stay the same.

Link:
https://akash.network/ecosystem/deployed-on-akash/dev%20tool/latest/1/

**Comment by brewsterdrinkwater** [comment]
Add the following orgs to the ecosystem page:

- [ ] Flock.io
- [ ] Brev.Dev
- [ ] Nous Research
- [ ] UT Austin - 
- [ ] Venice AI
- [ ] Thumper AI
- [ ] Auki Labs
- [ ] Nodeshift

**Comment by ShinySyntax** [comment]
Hello, @aktdenis 
I can do it.
Can I take on this issue?

**Comment by ShinySyntax** [comment]
Thanks

**Comment by aktdenis** [comment]
@brewsterdrinkwater  
Adding categories to each of the projects, links to twitter and website. 

+ we need to add project graphics (those can be grabbed from twitter) and descriptions

 Flock.io (AI&ML)
 twitter: https://twitter.com/flock_io web: https://www.flock.io/
 
 Brev.Dev (AI&ML)
 Twitter: https://twitter.com/brevdev  wweb: https://brev.dev/
 
 Nous Research (AI&ML)
twitter: https://twitter.com/NousResearch web: https://nousresearch.com/
 
 UT Austin (Education)
 Twitter:https://twitter.com/UTAustin Web: https://www.utexas.edu/
 
 Venice AI (AI&ML)
 Twitter: https://twitter.com/AskVenice Web: https://venice.ai/home
 
 Thumper AI (AI&ML)
 Twitter: https://twitter.com/ThumperAI Web: https://thumper.ai/
 
 Auki Labs (AI&ML)
 Twitter: https://twitter.com/AukiLabs Web: https://www.aukilabs.com/
 
 Nodeshift (Dev Tools) - Replace DeWeb Services, I think they renamed this project. Twitter:https://twitter.com/nodeshiftcloud Web: https://nodeshift.com/

**Comment by aktdenis** [comment]
@kindlyman343423 feel free to work on this one. appreciate your help

**Comment by ShinySyntax** [comment]
You are welcome

**Comment by aktdenis** [comment]
One more:

Prime Intellect
Text: Prime Intellect leverages Akash Supercloud's high-performance GPUs, like NVIDIA H100 and A100, to democratize AI development.
Twitter: Web: https://www.primeintellect.ai/ Web: https://twitter.com/PrimeIntellect

**Comment by aktdenis** [comment]
Adding two descriptions for:
Flock.io 
text: 
Flock.io is advancing open, decentralized AI by integrating with Akash's Supercloud, making it simple for developers to access high-performance compute for training AI models.

Brev.Dev (acquired by NVIDIA)
text: 
Brev.dev, known for its seamless setup of Jupyter notebooks for AI development, has integrated with Akash Network, enabling scalable, permissionless access to NVIDIA GPUs.

**Comment by ShinySyntax** [comment]
I got it.

**Comment by ShinySyntax** [comment]
Hello, @aktdenis 
I have done this task.
Plz check this.
https://github.com/akash-network/website/pull/338

**Comment by aktdenis** [comment]
@brewsterdrinkwater @HoomanDgtl @kindlyman343423 

i suggest we update this section with the same PR

<img width="1644" alt="Screenshot 2024-08-20 at 18 31 01" src="https://github.com/user-attachments/assets/8763f370-62a2-498e-82b8-1002369906a5">

maybe with these projects:
Venice AI
Brev.dev (acq. by NVidia)
Nous Research

cc @zachhorn for approval

**Comment by forbesus** [comment]
Hello @aktdenis 
I wanna contribute on this project

**Comment by ShinySyntax** [comment]
> @brewsterdrinkwater @HoomanDgtl @kindlyman343423
> 
> i suggest we update this section with the same PR
> 
> <img alt="Screenshot 2024-08-20 at 18 31 01" width="1644" src="https://private-user-images.githubusercontent.com/116030971/359564262-8763f370-62a2-498e-82b8-1002369906a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzU5NzUsIm5iZiI6MTcyNDE3NTY3NSwicGF0aCI6Ii8xMTYwMzA5NzEvMzU5NTY0MjYyLTg3NjNmMzcwLTYyYTItNDk4ZS04MmI4LTEwMDIzNjk5MDZhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNzQxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWVjMDYzNmVjMDIyY2EwZTY3N2Y1ZmM4ZThmODUxYjA0NjMzMzlmZWFkMWYwMjE1NDhhYmMwYzUyOWFlMzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.elFiVzDfCO6KT-2C-GyeqGZDYH1v22M16hlUOCw6imw">
> maybe with these projects: Venice AI Brev.dev (acq. by NVidia) Nous Research
> 
> cc @zachhorn for approval

Hello, @aktdenis 
I will take this.

**Comment by aktdenis** [comment]
hey @forbesus @ShinySyntax , thanks for showing interest in this issue. 
i'd like to hear @zachhorn thoughts before we proceed with implementation.

**Comment by aktdenis** [comment]
Here's a couple of things we need to do before closing this issue:

1. Let's move Nodeshift to "Dev tools" category:
<img width="436" alt="Screenshot 2024-08-26 at 14 08 56" src="https://github.com/user-attachments/assets/d9fbeccf-1655-43ea-b6e5-9f0a8fc36ced">

2. And remove "DeWeb Service" from "Dev tools". 
<img width="1355" alt="Screenshot 2024-08-26 at 14 09 07" src="https://github.com/user-attachments/assets/87c53c2d-bae3-44d1-a5ab-1d6e15a283e6">

3. Rename category "Dev tool" to "Dev tools" 

Thank you!

**Comment by ShinySyntax** [comment]
Ok, I will take this
@aktdenis

**Comment by ShinySyntax** [comment]
@aktdenis  I have done.
Plz check this.
https://github.com/akash-network/website/pull/346

**Comment by aktdenis** [comment]
couple of updates on the ecosystem page assigned to @HoomanDgtl:
- remove solve care and presearch
- move the projects we've just added to "showcase" (except shiftnode)
- change Brev.dev to Brev.dev (Acq. by NVIDIA)
-on the homepage let's go with only these projects: Venice AI, Brev,dev (Acq. by NVIDIA), Nous Research and rename the label "Deployed on Akash" to "Latest Integrations"

**Comment by aktdenis** [comment]
<img width="959" alt="Screenshot 2024-08-27 at 18 50 50" src="https://github.com/user-attachments/assets/03dfa772-11aa-4681-b6e2-04e49dd55538">

**Comment by aktdenis** [comment]
Updated description text for Nous: 
Leveraging the power of Akash's decentralized cloud, Nous Research successfully trained "Nous Hermes 2," an advanced AI model built on over 1,000,000 entries of GPT-4 data. 
cc @zachhorn for check

**Comment by ShinySyntax** [comment]
Ok, @aktdenis 
I will take this

**Comment by ShinySyntax** [comment]
https://github.com/akash-network/website/pull/349
@aktdenis 
I have done this

**Comment by aktdenis** [comment]
We would need to add these projects as well:
- Rango Exchange
Description:

category: Defi, website:https://rango.exchange/integrations , x-profile:https://twitter.com/RangoExchange

- Foundry Digital
Description:

category: Mining/Staking/Infrastructure, website:https://foundrydigital.com/ , x-profile:https://twitter.com/foundryservices

- Exabits
Description:

category: Infrastructure, website:https://www.exabits.ai/ , x-profile:https://twitter.com/exa_bits

- Nebula Block
Description:

category: Infrastructure, website: https://www.nebulablock.com/ , x-profile: https://twitter.com/nebulablockdata

- Neural AI
Description:

category: AI/ML, website:https://goneural.ai/ , x-profile:https://twitter.com/goneuralai

- Morpheus
Description:

category: AI/ML, website:https://mor.org/ , x-profile:https://twitter.com/MorpheusAIs

**Comment by ShinySyntax** [comment]
Ok, I will got it

**Comment by aktdenis** [comment]
@HoomanDgtl please close this issue

**Comment by HoomanDgtl** [comment]
this issue is resolved
