### ISSUE TITLE
Adding icons to menu item Network (dropdown)

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#34]
This issue was brought here for visibility and tracking purposes. 

It was mentioned a couple of times that the menu item "Network" which has a dropdown functionality could include icons. 

Here is a draft how that menu would look like:
<img width="207" alt="Screenshot 2024-02-22 at 10 03 35" src="https://github.com/akash-network/website-revamp/assets/116030971/5a697fbe-aa02-4a81-9697-fb7f63b156de">

Please note, the "providers" item was added to the preview here because of this [issue](https://github.com/akash-network/website-revamp/issues/16)

Menu was designed with tailwind components:
https://tailwindui.com/components/marketing/elements/flyout-menus

**Comment by aktdenis** [comment]
This issue is not finalized but serves as a starting point for further discussion and refinement. Feel free to share your thoughts and suggestions.

**Comment by aktdenis** [comment]
@baktun14 i believe you've brought this up during one of our calls (wg-website), so i created an issue.

**Comment by baktun14** [comment]
> @baktun14 i believe you've brought this up during one of our calls (wg-website), so i created an issue.

Yes, looks good!

**Comment by hiroyukikumazawa** [comment]
sent pr - https://github.com/akash-network/website/pull/214
please review

**Comment by HoomanDigital** [comment]
closing this now as plan is to revamp whole menu items
