### ISSUE TITLE
GPU count does not update when filtered

### ISSUE THREAD

**Issue by gosuri** [akash-network/website#355]
It takes manual calculation to understand which GPUs are available when filtered.

<img width="1429" alt="Screenshot 2024-08-30 at 9 54 58 AM" src="https://github.com/user-attachments/assets/729c5237-85da-49e9-8906-918fbfe4a9c9">

**Comment by HoomanDgtl** [comment]
fixed #356

**Comment by gosuri** [comment]
🔥
