### ISSUE TITLE
smart phone global menu is necessary to update !

### ISSUE THREAD

**Issue by conveyGhost** [akash-network/website#366]
![image](https://github.com/user-attachments/assets/7f309bde-ae93-42ee-aa6c-573f5fe17159)
As you can see, the entire frame of the smart phone does not fill.
![image](https://github.com/user-attachments/assets/070d3892-9361-4685-a3cf-67d20835a2a7)
I think there should be no hidden parts.

**Comment by aktdenis** [comment]
thanks @conveyGhost , there is a new PR ready with a redesigned menu experience

**Comment by aktdenis** [comment]
@HoomanDgtl please close this issue
