### ISSUE TITLE
Replace logo "sdxl on akash" with "akash sdxl"

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#374]
To align all current products with the same style of branding and naming, I'm suggesting we change the logo "sdxl on akash" with "akash sdxl".
<img width="1697" alt="Screenshot 2024-09-25 at 14 21 52" src="https://github.com/user-attachments/assets/040d41e3-9489-4fc8-ad6a-6e84e1385505">

updated logo:
![akash-sdxl](https://github.com/user-attachments/assets/858f53b7-a7dc-43b2-bcd1-e329828e659a)

for any possible volunteers who are willing to work on this issue, please find the SVG here:
[akash-sdxl.svg.zip](https://github.com/user-attachments/files/17130820/akash-sdxl.svg.zip)

--

please note, there is no bounty available for this issue.

**Comment by forbesus** [comment]
Hello @aktdenis 
I will take this issue
