### ISSUE TITLE
Events page UI/UX Updates

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#389]
Sharing a couple of updates we would like to see for Akash Events page.

Currently the link for events is: akash.network/community/events/upcoming
it should point to: akash.network/community/events/

Current + upcoming events should be the default. That's why we are removing "All" + "Upcoming" toggle.

<img width="1718" alt="Screenshot 2024-10-10 at 13 04 54" src="https://github.com/user-attachments/assets/a755d1fe-8600-4cf4-8dd3-e696608930d3">

We're adding a 'See past events in the archive' button at the bottom of the page, which will direct users to the event archive (akash.network/community/events/archived/). Events will automatically be moved to the archive once they've passed. Note that the archive will only store events from the past year for easy reference. Functionality of the page stays the same when viewing "archived events", we will just state that in the subheadline; "Explore the list of Past Events".

Couple of styling issues we would like to solve as well:
- Headline + copy is centered
- Increase margin space (left,right)
- Event Description text needs to be lighter (currently semibold, see below) 
<img width="395" alt="Screenshot 2024-10-10 at 13 18 42" src="https://github.com/user-attachments/assets/16069687-f37e-4916-b3a3-777c4f12ea44">

Sharing a mockup of look+functionality we would like to achieve below:

<img width="815" alt="Screenshot 2024-10-10 at 13 20 12" src="https://github.com/user-attachments/assets/bc28b000-0f5a-4ffb-8555-6fa9e5c5e86b">

--

If you're interested in contributing to this issue, please provide a time and cost estimate for implementation. For more information or clarification, feel free to reach out.

**Comment by piber-dev** [comment]
hi @aktdenis is it correct to assume that you want two pages: `akash.network/community/events/` & `akash.network/community/events/archived/`, do you want the functionality to be at the same page just that it loads all of the archived events by the click of a button, or are you expecting gradual loading of events, future-proofing the loading of the events for when there are many more? are you expecting events to automatically go to the archive after the date is up, or moving events be a manual effort?

**Comment by aktdenis** [comment]
@piber-dev thanks for fleshing out the details of this issue! I've updated my comment

**Comment by piber-dev** [comment]
@aktdenis i think this would be a good first real issue for me here. is 10 hours @ $50/hr reasonable? the $50/hr has been used previously a lot for many proposals and bounties. i'm not super familiar with this repository yet so can't say what a reasonable time is to familiarize myself with the repository and complete the work.

**Comment by aktdenis** [comment]
@piber-dev Thanks for showing interest in getting this done! However, I do need to let you know that budget for this task is $30/hr. If you're still interested in moving forward, please let me know.

**Comment by piber-dev** [comment]
thanks for this opportunity @aktdenis, i will take it^^ time will tell if it makes sense economically for sporadical contributions but i'm happy to try it out to gain experience. i will begin work tomorrow and i am hoping to have it finished for a first review early next week.

for future reference, what makes different tasks have different budgets? i am thinking out loud here, feel free not to respond. $35-$53/hr is about the range needed from entry-level to experienced web developers in sweden, with added taxes/misc overhead & an 8% standard profit margin assuming no other costs and scheduling 8 hours of contract work per day which is unrealistic.

**Comment by HoomanDgtl** [comment]
Hi @aktdenis, it would be great if you could clarify the direction for the CTA 'Explore past events.'

Also, thank you @piber-dev for showing interest. Please confirm if you're willing to take on the issue with the following terms:

Deadline: 2 days
Estimated hours: 10

Thanks!

**Comment by piber-dev** [comment]
hello @HoomanDgtl, 2 working days deadline sounds fair, so deadline on the evening of monday. i confirm these terms.

**Comment by Bct-crypto** [comment]
Hi @aktdenis 
I am interested in contributing to this issue.
I have researched Akash website deeply and I am sure that this can be done.
I can work for $30/h.
I can finish this by Monday morning.
Estimated hours is 10~15h.
Please let me know if I can start this task.

**Comment by piber-dev** [comment]
hello @Bct-crypto i already confirmed that i will work on this issue but you can take a look at other issues in this repository or incase i don't meet the deliverables you can take over from there. maybe [this](https://github.com/akash-network/website/issues/383) issue is something you can work on? @HoomanDgtl already wrote that their team can work on that one but never mentioned any estimates or resources required.

**Comment by Bct-crypto** [comment]
> hello @Bct-crypto i already confirmed that i will work on this issue but you can take a look at other issues in this repository or incase i don't meet the deliverables you can take over from there. maybe [this](https://github.com/akash-network/website/issues/383) issue is something you can work on? @HoomanDgtl already wrote that their team can work on that one but never mentioned any estimates or resources required.

Hi @piber-dev, @HoomanDgtl,

Thank you for clarifying the status of the issue. I see that @piber-dev has already committed to working on it. I'll keep an eye on the progress, and if there's any need for additional support or if the deliverables aren't met, I'd be happy to assist at that point.

In the meantime, I'll explore other issues in the repository and remain available for future tasks.

Best of luck with the implementation, and feel free to reach out if needed!

**Comment by aktdenis** [comment]
> thanks for this opportunity @aktdenis, i will take it^^ time will tell if it makes sense economically for sporadical contributions but i'm happy to try it out to gain experience. i will begin work tomorrow and i am hoping to have it finished for a first review early next week.
> 
> for future reference, what makes different tasks have different budgets? i am thinking out loud here, feel free not to respond. $35-$53/hr is about the range needed from entry-level to experienced web developers in sweden, with added taxes/misc overhead & an 8% standard profit margin assuming no other costs and scheduling 8 hours of contract work per day which is unrealistic.

great and thank you! looking forward to these updates.
it's a budget we have for this task, and the task itself is entry-level.

**Comment by aktdenis** [comment]
Hey @Bct-crypto thanks for showing interest. 
I'll be adding new issues, so stay tuned and keep an eye on our discord channel; wg-akash-website

**Comment by piber-dev** [comment]
hi @aktdenis - quick update before the weekend and hopefully questions you can answer if they are relevant. otherwise, enjoy your weekend.

i have added two constants: archivedCards and relevantCards and made functionality that made events be archived 1 week after the date has passed. i thought this was a good addition as events can sometimes be active for a few days, and archiving doesn't need to happen instantly. in fact, this 1 week offset can likely be doubled or otherwise in case someone is trying to see more information of this event from the website.

font weight for the description was not semibold, it was set to medium. i changed this to normal (1 step less than semibold). it looks good now. the other two styling issues you mentioned (referenced below), i'm guessing this is to make it look like the mockup, not that these are actual issues? also do you want events to no longer be categorized by the month ("1 row per month") but rather all placed out in order like the mockup? or do you just want it to be centered? the removal of month headers in the mockup and non-unique events picked makes it hard for me to guess.

> Headline + copy is centered
> Increase margin space (left,right)

if no answer is given in time, i will assume for now that you want the month headers to be removed and for the same functionality to take place, just centered.

**Comment by aktdenis** [comment]
hey @piber-dev, sharing answers below 
> 
> i have added two constants: archivedCards and relevantCards and made functionality that made events be archived 1 week after the date has passed. i thought this was a good addition as events can sometimes be active for a few days, and archiving doesn't need to happen instantly. in fact, this 1 week offset can likely be doubled or otherwise in case someone is trying to see more information of this event from the website.
>
-- good idea for sure, thanks! 10 days after event has passed is fine.

> 
> font weight for the description was not semibold, it was set to medium. i changed this to normal (1 step less than semibold). it looks good now. the other two styling issues you mentioned (referenced below), i'm guessing this is to make it look like the mockup, not that these are actual issues? also do you want events to no longer be categorized by the month ("1 row per month") but rather all placed out in order like the mockup? or do you just want it to be centered? the removal of month headers in the mockup and non-unique events picked makes it hard for me to guess.
>
-- perfect! no need for months, all placed as mockup. i can share figma file, just add me on discord.

> 
> > Headline + copy is centered
> > Increase margin space (left,right)
> 
> if no answer is given in time, i will assume for now that you want the month headers to be removed and for the same functionality to take place, just centered.
>
-- appreciate your help!

**Comment by piber-dev** [comment]
hello guys, happy monday. i created a PR for the UX updates now while i am waiting for @aktdenis to send me the figma file and i am also requesting more time within reason for copying the styling from the figma file @HoomanDgtl as i am waiting for access.

**Comment by piber-dev** [comment]
hello @aktdenis please review PR https://github.com/akash-network/website/pull/391 for any notes or feedback, it is updated with UI/design changes now

**Comment by HoomanDgtl** [comment]
this is resolved
