### ISSUE TITLE
Akash Events - Unify size of the graphics 

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#396]
Graphics used across the Akash Events page are inconsistent in size, leading to a disjointed visual experience. Some images appear smaller or larger than others, which impacts the overall layout and presentation of the page.

<img width="1666" alt="Screenshot 2024-10-16 at 14 41 37" src="https://github.com/user-attachments/assets/e7d1d4ac-91ea-4e01-9aab-ef8aaf198040">

Fix: standardize the dimensions of all event graphics to 1200x630 to create a uniform look and feel.
<img width="1044" alt="Screenshot 2024-10-16 at 14 46 32" src="https://github.com/user-attachments/assets/53d39887-48fa-48d1-b7d7-703a7240a806">

--

If you’re interested in fixing this issue, please provide an estimate for the time and effort involved. Let me know if you need access to any specific assets or resources to complete this task.

**Comment by forbesus** [comment]
Hello @aktdenis 
I will take this issue
My hourly rate is $35/h and I can finish this in 20 hours

Thank you

**Comment by aktdenis** [comment]
@forbesus i'm not sure if you've read this issue correctly. we need to resize 4 images and upload them. budget for this issue is one hour, $30/h.

**Comment by forbesus** [comment]
I am sorry for my confusing.
I thought I have to fix css part to upload any image not resizing image

10 hours are enough for resizing images and I agree with your hourly rate

**Comment by aktdenis** [comment]
@forbesus thanks for showing interest. the budget is actually 1 hour. if there are no takers i'll upload new images by myself.

**Comment by forbesus** [comment]
You mean you have resizing images and just need to upload it?

**Comment by ShinySyntax** [comment]
@aktdenis 
I will take this issue.
Thanks.

**Comment by aktdenis** [comment]
@ShinySyntax the budget is 1h, $30/h. if you can manage it, feel free to do it

**Comment by leonkertmaster** [comment]
@aktdenis can i also take the issue?

**Comment by aktdenis** [comment]
this issue is assigned to @ShinySyntax. 
he's already working on it and has the images ready

**Comment by aktdenis** [comment]
@HoomanDgtl PR ready. When merged, please close it. thanks!

**Comment by HoomanDgtl** [comment]
this is resolved
