### ISSUE TITLE
create sub pages for whitepaper and economics

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website#404]
- [ ] "/whitepaper "redirect to https://ipfs.io/ipfs/QmVwsi5kTrg7UcUEGi5UfdheVLBWoHjze2pHy4tLqYvLYv
- [ ] "/economics" redirect to https://ipfs.io/ipfs/QmdV52bF7j4utynJ6L11RgG93FuJiUmBH1i7pRD6NjUt6B
- [ ] update footer for respective links

**Comment by forbesus** [comment]
hello @brewsterdrinkwater 
i will take this issue

**Comment by hiroyukikumazawa** [comment]
Here are the links to the code updated by @forbesus :
http://65.109.84.205:4321/
http://65.109.84.205:4321/economics
http://65.109.84.205:4321/whitepaper

**Comment by hiroyukikumazawa** [comment]
> Here are the links to the code updated by @forbesus : http://65.109.84.205:4321/ http://65.109.84.205:4321/economics http://65.109.84.205:4321/whitepaper

@brewsterdrinkwater did you check these?

**Comment by HoomanDgtl** [comment]
this is resolved
