### ISSUE TITLE
Ecosystem updates / Consolidating the "Showcase" and "Deployed on Akash" pages

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#413]
We want to streamline the user experience by consolidating the "Showcase" and "Deployed on Akash" pages. This change involves:

Keeping only the "Deployed on Akash" page.
Adding a new "Showcase" category in the left vertical navigation, placed directly under the "All" item.
Ensuring that when users land on this page, the "Showcase" category is selected and active by default, rather than "All".
<img width="1362" alt="Screenshot 2024-11-13 at 21 25 08" src="https://github.com/user-attachments/assets/1932493f-dbc9-4dad-ba74-f03ef182e6f4">

Menu Update:
Reflect the new structure in the site menu by removing "Showcase" as a standalone page and making it a category within "Deployed on Akash". Ensure that the menu items in the main navigation are ordered with "Deployed on Akash" appearing first, followed by "Tools". 
<img width="1862" alt="Screenshot 2024-11-13 at 21 18 19" src="https://github.com/user-attachments/assets/a0d5389b-8f25-4221-b264-6ed228831e29">

Please ensure all existing showcase content is migrated seamlessly to the "Deployed on Akash" page.

**Comment by ShinySyntax** [comment]
I will take this issue.

**Comment by piber-dev** [comment]
if the issue is still here next week i can also offer to take it. guessing this takes about an hour or two? lets say two and let me know if you want me to work on it or if you want this resolved before the weekend.

EDIT: after todays meeting (2024-11-14) would like to up this to 3 hours as it included some additional UI updates related to moving some elements, assuming nothing else after this.

**Comment by ShinySyntax** [comment]
> if the issue is still here next week i can also offer to take it. guessing this takes about an hour or two? lets say two and let me know if you want me to work on it or if you want this resolved before the weekend.

I can't believe this guy's saying

**Comment by piber-dev** [comment]
hi @ShinySyntax feel free to take this issue if you are able to work on it. i just commented because you didn't include a time estimate, which usually turns into a lot of back and fourth's between you and @aktdenis, so just wanted to offer my availability and a time estimate if this were to happen again to not waste time.

**Comment by ShinySyntax** [comment]
> hi @ShinySyntax feel free to take this issue if you are able to work on it. i just commented because you didn't include a time estimate, which usually turns into a lot of back and fourth's between you and @aktdenis, so just wanted to offer my availability and a time estimate if this were to happen again to not waste time.

If you can finish it in 2 hours, feel free to start. 
I just doubted your ability.

**Comment by HoomanDgtl** [comment]
Hii @ShinySyntax : as you asked first, could you please mention your hourly rate and estimated time to complete the work.

Thanks.

**Comment by hylcore-V** [comment]
is there any chance to contribute for solving this issue?

**Comment by piber-dev** [comment]
@hylcore-V if no agreement is made with @ShinySyntax, yes. the group would prefer to get it done before/during the weekend rather than after.

**Comment by ShinySyntax** [comment]
> Hii @ShinySyntax : as you asked first, could you please mention your hourly rate and estimated time to complete the work.
> 
> Thanks.

Thanks for your contact.
My duration time is 10 hours and hourly rate is 30$.
I can complete within this week

**Comment by hylcore-V** [comment]
> @hylcore-V if no agreement is made with @ShinySyntax, yes. the group would prefer to get it done before/during the weekend rather than after.

Okay.
I'd be happy if you let me know the result as soon as possible so that I can finished it in time.
And I think @ShinySyntax 's price and timeline is suitable.

**Comment by aktdenis** [comment]
this issue is already solved. thank you guys! I'll prepare a new one asap
