### ISSUE TITLE
Take rates image is outdated

### ISSUE THREAD

**Issue by piber-dev** [akash-network/website#423]
the image below also found on the [token page](https://akash.network/token/) is outdated. ever since [prop 267](https://www.mintscan.io/akash/proposals/267) passed, take rates are 1% for AKT and 2% for USDC. the rest looks accurate after double checking against the [parameters page](https://www.mintscan.io/akash/parameters). does anyone have access to this file to change it?

![image](https://github.com/user-attachments/assets/ee16f549-8a4a-41ac-8560-bcdebd8130a8)

**Comment by aktdenis** [comment]
thank you @piber-dev. i got the image and can share figma file if anyone is interested to update it. 

<img width="1938" alt="Screenshot 2024-11-28 at 14 27 27" src="https://github.com/user-attachments/assets/782a2da0-c4de-489f-9191-e43ac8da95d5">

**Comment by hiroyukikumazawa** [comment]
Let me handle this issue.

**Comment by HoomanDgtl** [comment]
@aktdenis A dark mode version of the image would also be required.
thanks

**Comment by hiroyukikumazawa** [comment]
> the image below also found on the [token page](https://akash.network/token/) is outdated. ever since [prop 267](https://www.mintscan.io/akash/proposals/267) passed, take rates are 1% for AKT and 2% for USDC. the rest looks accurate after double checking against the [parameters page](https://www.mintscan.io/akash/parameters). does anyone have access to this file to change it?


I couldn't find the image in the [token page](https://akash.network/token/)

**Comment by piber-dev** [comment]
if you are unable to fix it @hiroyukikumazawa i can do it after @aktdenis shares the figma file

**Comment by HoomanDgtl** [comment]
@hiroyukikumazawa here: https://akash.network/token/#akt-features

**Comment by HoomanDgtl** [comment]
> if you are unable to fix it @hiroyukikumazawa i can do it after @aktdenis shares the figma file

thank you @piber-dev , really appreciate it..

**Comment by HoomanDgtl** [comment]
@piber-dev do you wanna work on other issues that are open? you can comment down your interest and we will consider.

**Comment by piber-dev** [comment]
hi @HoomanDgtl sorry for reading this late. i am currently working on a bigger project in the background so i will leave the current issues to other people. but if this still needs to be resolved, i am still available for this issue. thanks!

**Comment by HoomanDgtl** [comment]
this is resolved.
