### ISSUE TITLE
Reduce line length on website for better readability

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#431]
currently, some sections of the website display text with lines exceeding 150+ characters, which negatively impacts readability and user experience.

example in the third line here 178 characters; https://akash.network/development/welcome/
optimal line length for comfortable reading is around 70-80 characters per line.

what fix would look like:
- increase left and right margins or padding in text containers to reduce the line length
- test adjustments across different screen sizes to maintain responsiveness and readability

--
** issue not related to blog posts, number of characters there are okey

**Comment by hiroyukikumazawa** [comment]
Let me handle this issue.

**Comment by Bct-crypto** [comment]
I can do it.

**Comment by Bct-crypto** [comment]
plz let me know if I can start work

**Comment by aktdenis** [comment]
hey @Bct-crypto , if you’re interested in contributing to this issue, here’s what we’ll need from you:

- an estimate of the time and effort required to complete the work.
- a proposed timeline for when it’ll be finished.

for your contribution to be accepted:

- ensure your changes align with the issue description/ goals
- follow the design and content standards of the akash network website
- make sure the updates are responsive and function properly across devices/browsers
- provide clean, well-documented code or assets for any updates made
- use conventional commits for all commit messages to maintain consistency and clarity 

pay close attention to the current codebase, design, and website behavior to ensure your updates integrate seamlessly. also, carefully follow the provided content and designs to implement them as specified. failure to apply them correctly can lead to additional feedback loops and rework, delaying the process.

if you have questions or need clarification during the process, don’t hesitate to reach out. 
appreciate your effort

**Comment by Bct-crypto** [comment]
hi @aktdenis 
sure, i can help out with this issue.
1. time & effort - this should take me around 5~6h to complete. it's a decent-sized task, but nothin' too crazy.
2. timeline - i can get this done, depending on any feedback or changes that come up along the way.

i'll keep a close eye on the current codebase, design, and website behavior to make sure my updates integrate smoothly. i'll also closely follow the provided content and designs to implement them as specified.
plz share me figma file.
if any questions or issues come up, i'll reach out right away. let's get this done!

**Comment by HoomanDgtl** [comment]
@aktdenis lmk if we good to go on this issue and I will assign this to @Bct-crypto . thanks

**Comment by Bct-crypto** [comment]
plz share me figma file.

**Comment by HoomanDgtl** [comment]
@Bct-crypto , you can refer to images in this issue to see the margin in the left and right: https://github.com/akash-network/website/issues/432

This issue is assigned to you..

reach out to me on discord: (boldpanther) if you need clarification

**Comment by HoomanDgtl** [comment]
this is resolved.
