### ISSUE TITLE
update COMMUNITY pages: new text, graphics, and page restructuring

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#432]
we need to do somee updates on the community pages... the changes include introducing updated texts and graphics, removing outdated sections (community contributions)

updating page: 
akash insiders
* includes a horizontal gallery slider
<img width="845" alt="Screenshot 2024-11-28 at 14 42 06" src="https://github.com/user-attachments/assets/b3cdae36-f184-48df-98c2-bfa95296fa08">

updating page: 
akash validators
<img width="792" alt="Screenshot 2024-11-28 at 14 42 42" src="https://github.com/user-attachments/assets/fd60f767-fc83-4dc5-b2d6-61e48620b7b6">

bringing back page
Akash EDU
<img width="706" alt="Screenshot 2024-11-28 at 14 43 10" src="https://github.com/user-attachments/assets/076a652a-2eed-4a58-8940-ad1e0bc9ef07">

for anyone interested in tackling this issue there is a figma file with new text and graphics available.
please note that we need to insure these pages are responsive and work in dark mode.
and also implementation of this issue: https://github.com/akash-network/website/issues/431

**Comment by hiroyukikumazawa** [comment]
Let me handle this issue.

**Comment by Bct-crypto** [comment]
I can do it.
plz share me figma flie.

**Comment by aktdenis** [comment]
hey @Bct-crypto , if you’re interested in contributing to this issue, here’s what we’ll need from you:

- an estimate of the time and effort required to complete the work.
- a proposed timeline for when it’ll be finished.

for your contribution to be accepted:

- ensure your changes align with the issue description/ goals
- follow the design and content standards of the akash network website
- make sure the updates are responsive and function properly across devices/browsers
- provide clean, well-documented code or assets for any updates made
- use conventional commits for all commit messages to maintain consistency and clarity 

pay close attention to the current codebase, design, and website behavior to ensure your updates integrate seamlessly. also, carefully follow the provided content and designs to implement them as specified. failure to apply them correctly can lead to additional feedback loops and rework, delaying the process.

if you have questions or need clarification during the process, don’t hesitate to reach out. 
appreciate your effort

**Comment by Bct-crypto** [comment]
hi @aktdenis 
sure, i can help out with this issue.
1. time & effort - this should take me around 5~6h to complete. it's a decent-sized task, but nothin' too crazy.
2. timeline - i can get this done, depending on any feedback or changes that come up along the way.

i'll keep a close eye on the current codebase, design, and website behavior to make sure my updates integrate smoothly. i'll also closely follow the provided content and designs to implement them as specified.
plz share me figma file.
if any questions or issues come up, i'll reach out right away. let's get this done!

**Comment by HoomanDgtl** [comment]
thank you @Bct-crypto for showing your interest in this, I am assigning this issue to you..

Lets get it done by Monday..

thank you

**Comment by Bct-crypto** [comment]
got it

**Comment by HoomanDgtl** [comment]
this is resolved.
