### ISSUE TITLE
update FUNDING PROGRAMS page

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#433]
the funding programs page needs updates. this includes adding updated texts and graphics...

tasks:
- replace existing text with new, approved content
- include new visuals/graphics

preview:
<img width="751" alt="Screenshot 2024-11-28 at 14 50 55" src="https://github.com/user-attachments/assets/ca4f7bc7-349a-4ee3-8aa3-3507262d8609">

please ensure the fix includes this issue:
https://github.com/akash-network/website/issues/431

**Comment by hiroyukikumazawa** [comment]
Let me handle this issue.

**Comment by Bct-crypto** [comment]
If you share me figma, I can do it

**Comment by aktdenis** [comment]
hey @Bct-crypto , if you’re interested in contributing to this issue, here’s what we’ll need from you:

- an estimate of the time and effort required to complete the work.
- a proposed timeline for when it’ll be finished.

for your contribution to be accepted:

- ensure your changes align with the issue description/ goals
- follow the design and content standards of the akash network website
- make sure the updates are responsive and function properly across devices/browsers
- provide clean, well-documented code or assets for any updates made
- use conventional commits for all commit messages to maintain consistency and clarity 

pay close attention to the current codebase, design, and website behavior to ensure your updates integrate seamlessly. also, carefully follow the provided content and designs to implement them as specified. failure to apply them correctly can lead to additional feedback loops and rework, delaying the process.

if you have questions or need clarification during the process, don’t hesitate to reach out. 
appreciate your effort

**Comment by Bct-crypto** [comment]
hi @aktdenis 
sure, i can help out with this issue.
1. time & effort - this should take me around 5~6h to complete. it's a decent-sized task, but nothin' too crazy.
2. timeline - i can get this done, depending on any feedback or changes that come up along the way.

i'll keep a close eye on the current codebase, design, and website behavior to make sure my updates integrate smoothly. i'll also closely follow the provided content and designs to implement them as specified.
plz share me figma file.
if any questions or issues come up, i'll reach out right away. let's get this done!

**Comment by HoomanDgtl** [comment]
hii @Bct-crypto , I am keeping this issue open for others as two of the issues are already assigned to you.. #431 #432

If no one shows interest in the meantime then we will decide to move forward with you..

Thank you

**Comment by Bct-crypto** [comment]
okay

**Comment by Abhishek7Tech** [comment]
Hey @HoomanDgtl, @Bct-crypto  , 

I would like to update the FUNDING PROGRAMS page.

time required: 1-3 days as I am also working on a freelance project.

**Comment by leonkertmaster** [comment]
@aktdenis @HoomanDgtl I'd like to take on this issue. It will take me approximately 3 hours to complete, at a rate of $30/hour. Thanks!

**Comment by HoomanDgtl** [comment]
@Abhishek7Tech could you please mention the time it would take for you to complete this? Also let us know if you would be able to complete this by Tuesday.

thanks

**Comment by HoomanDgtl** [comment]
@leonkertmaster Thank you for the offer. However, we typically expect some GitHub activity, relevant trackable experience, or prior engagement with Akash before allowing contributions.  

Could you share your previous work experience, expertise, or open-source contributions? This will help us better gauge your skills.  

Thanks!

**Comment by Abhishek7Tech** [comment]
@HoomanDgtl Yes I can complete this by Tuesday if I start today. 

Previous work experience: 
![Screenshot 2024-12-02 111832](https://github.com/user-attachments/assets/fad6e2b8-e6d4-473f-bf41-38aea2936910)


My portfolio: Portfolio- http://abhishek-web-dev.netlify.app/

Open Source contributions:
http://github.com/dogdb-org,
https://github.com/acm-uic/sparkhacks-2023,
https://github.com/LasticXYZ/LasticUI,
https://github.com/evershopcommerce/evershop,
https://github.com/Utkarshn10/Focusly 

Also, I was featured in Chompdotgames for my contributions: 
https://x.com/chompdotgames/status/1811792615932588265

**Comment by HoomanDgtl** [comment]
thanks @Abhishek7Tech : Could you please specify the estimated number of hours and your hourly rate required to complete this?

**Comment by Abhishek7Tech** [comment]
@HoomanDgtl 

Looking at the jpg file above - It will take me 3-5 hours.

Scope of work - Adding content, Implementing dark and light modes, View more button functionality, and adding responsiveness for all screen sizes.
 
Hourly rate - $20/hr

**Comment by HoomanDgtl** [comment]
thanks @Abhishek7Tech : this issue is assigned to you.
here is the figma file: [click here](https://www.figma.com/design/bwIGCoaV1dPVyrKR45lRmg/akash-web-issues-november?node-id=4-2202&t=7KveNE6eRUl3cPMw-1)

if you need help, reach out on discord: boldpanther

thanks

**Comment by Abhishek7Tech** [comment]
Hey @HoomanDgtl

I have made a PR: https://github.com/akash-network/website/pull/436

**Comment by HoomanDgtl** [comment]
this is resolved.
