### ISSUE TITLE
update: token exchanges

### ISSUE THREAD

**Issue by HoomanDgtl** [akash-network/website#438]
The list of exchanges offering access to the AKT token has grown.  
Task is to update the token page to include all reputable exchange platforms that provide AKT tokens.  

Thank you.

**Comment by Bct-crypto** [comment]
I can do it

**Comment by Abhishek7Tech** [comment]
I would like to work on this.

**Comment by HoomanDgtl** [comment]
@Bct-crypto please specify the time and how you plan to do it?
thanks

**Comment by Bct-crypto** [comment]
@HoomanDgtl  I think it will be take 4~5 hours.
thank you

**Comment by aktdenis** [comment]
@Bct-crypto which exchanges are you planning to add?

**Comment by Bct-crypto** [comment]
@aktdenis 
**CEX:** 
- BingX
- Bithumb
- XT.COM
- Bitvavo
- Hotcoin
- Phemex
- AscendEX(BitMax)
- Bitrue
- CoinDCX
- HitBTC
- Hibt
- BitKan
- Korbit
- ChangeNow

**DEX:**

- Kujira Fin

**Comment by aktdenis** [comment]
Sorry @Bct-crypto, but 5hours is way too much for this kind of task. Someone from the finance team will take care of this issue. Thanks for showing interest!

**Comment by Bct-crypto** [comment]
@aktdenis I can do it in 1 hour

**Comment by Bct-crypto** [comment]
@aktdenis It took some time to research DEX and CEX.

**Comment by HoomanDgtl** [comment]
Thanks @Bct-crypto for the effort but this is something that is very sensitive topic and hence the core team will tc of it.. 

You can always apply to other issues.. 

Thanks

**Comment by Bct-crypto** [comment]
got it

**Comment by Bct-crypto** [comment]
I can handle https://github.com/akash-network/website/issues/439

**Comment by HoomanDgtl** [comment]
this is resolved.
