### ISSUE TITLE
Add a sticky button for DEVELOPMENT page with a calendar pop-up

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#439]
we would like to add a sticky button that allows users to access the calendar at any time - [on these pages](https://akash.network/development/welcome/). 

the button should stick to the bottom-right corner of the page and remain visible as users scroll. clicking on the button should trigger a pop-up displaying the calendar, along with a clear call-to-action (CTA) to subscribe to the SIG & WG calendar.

preview of a button:
<img width="971" alt="Screenshot 2024-12-04 at 17 41 43" src="https://github.com/user-attachments/assets/67317227-2fd8-4764-ab82-c724f74f532d">

preview of a calendar:
<img width="979" alt="Screenshot 2024-12-04 at 17 47 52" src="https://github.com/user-attachments/assets/a0b6751a-de45-4e39-8ab0-780909c189fd">

once this is implemented, the calendar currently located under development > get involved should be removed to avoid redundancy.

important detail:
this change does not involve any technical updates to the calendar itself. we will continue to use the same google calendar, and the pop-up will simply display its content.

tasks:
1 add sticky button:
- create a sticky button positioned at the bottom-right corner of the "development" page.
- ensure the button remains visible at all times while scrolling.
2. implement calendar pop-up:
- clicking the sticky button should open a pop-up displaying the calendar.
3. remove existing calendar:
- remove the calendar currently located in the development > get involved section of the page.
---
all of the above should work seamlessly in different breakpoints (fully responsive) +  dark mode

please note:
carefully follow the provided content and designs to implement them as specified. failure to apply them correctly can lead to additional feedback loops and rework, delaying the process.

if you’re interested in contributing to this issue, here’s what we’ll need from you:
- an estimate of the time and effort required to complete the work.
- a proposed timeline for when it’ll be finished.

if you have questions or need clarification during the process, don’t hesitate to reach out.

**Comment by Bct-crypto** [comment]
hi @aktdenis I can do it.
I think it will be take about 5~6 hours.
thank you

**Comment by aktdenis** [comment]
hi @Bct-crypto, could you provide a timeline and your hourly rate?
thank you

**Comment by Bct-crypto** [comment]
my hourly rate is $30
I can finish it until tomorrow.

**Comment by HoomanDgtl** [comment]
Assigning this task to you @Bct-crypto

**Comment by aktdenis** [comment]
hey @Bct-crypto, here's the figma file:
[akash-dev-calendar.fig.zip](https://github.com/user-attachments/files/18021982/akash-dev-calendar.fig.zip)
appreciate your contribution and looking forward to see it live.

**Comment by Bct-crypto** [comment]
hi @aktdenis 
Thank you for sharing the Figma file! I'll review the design thoroughly and ensure it aligns perfectly with the implementation. I’m excited to bring this to life and will keep you updated on the progress.

**Comment by Bct-crypto** [comment]
https://github.com/akash-network/website/pull/441

**Comment by Bct-crypto** [comment]
plz check this

**Comment by Bct-crypto** [comment]
hi @aktdenis @HoomanDgtl 
plz check this:
https://github.com/akash-network/website/pull/449

**Comment by HoomanDgtl** [comment]
this is resolved in #451
