### ISSUE TITLE
extra spacing on each page of the documentation

### ISSUE THREAD

**Issue by tgrecojs** [akash-network/website#50]
looking through the docs I found that each page had an unnecessary amount of spacing between the top of the page and the first appearance of any words. I noticed that there is always at least one line of bit of spacing below the metadata atop each page, so I just took a second to do a bulk removal of this space only to learn that this is not a valid fix as the spacing still appeared. 

**It must be a global setting that needs to be changed in order for this to be fixed.** I'm not sure what the setting is though so rather than sink any time into it i'm opening this issue. Additionally, some feedback would be appreciated as I want to ensure i'm not alone in feeling as though this spacing is a bit odd.

Below are screenshots from the new docs.

When there is some heading text to start the page, then it can go unnoticed. I still think that it warrants fixing though.

![ss_03042024_000186](https://github.com/akash-network/website-revamp/assets/6646552/b0ee87ad-77dc-4bc0-8e7b-d5051b57109a)

Without heading text the extra spacing is very noticeable imo. 

![ss_03042024_000185](https://github.com/akash-network/website-revamp/assets/6646552/2a7a5331-7b9b-4e09-8193-4db5a5148250)

**Comment by aktdenis** [comment]
@tgrecojs good call. thank you!
