### ISSUE TITLE
Repositioning of the "Get Started" section

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#60]
I suggest moving the "Get Started" section to a prominent position above the fold on the homepage. This change aims to immediately engage visitors, guiding them on the Akash Network journey from the moment they arrive on the site.

This repositioning provides an opportunity to introduce an additional card dedicated to showcasing GPUs on Akash Network. It could highlight the availability of GPUs, potentially driving more users to leverage this feature.

Design Proposal
<img width="1378" alt="Screenshot 2024-03-15 at 14 38 46" src="https://github.com/akash-network/website-revamp/assets/116030971/7fcfd19b-770a-4887-a9a5-fb8c9f578dd1">

cc @zachhorn for content

**Comment by aktdenis** [comment]
This issue is not finalized but serves as a starting point for further discussion and refinement. Feel free to share your thoughts and suggestions.

**Comment by zachhorn** [comment]
I love this, let's implement asap.

I'll draft initial copy in figma

**Comment by aktdenis** [comment]
thanks @zachhorn for a quick update. here is a mockup with the latest figm:
<img width="1331" alt="Screenshot 2024-03-15 at 16 18 13" src="https://github.com/akash-network/website-revamp/assets/116030971/15ced737-9520-4cce-bd64-3dbf5dcdcb28">

@HoomanHQ please review and provide an estimate when could we expect this live. and please note, we would remove the "get started" from the homepage since we're covering everything with this new section. 

**gpus list and pricing page is in the making, when it will be available please link to that page. thank you!

**Comment by aktdenis** [comment]
@HoomanHQ i would leave it, so it's reachable when users are browsing through other pages

**Comment by aktdenis** [comment]
cta for deployments here: https://akash.network/deploy/
cta for providers here: https://akash.network/providers/
in this case we could always have "get started" in the main menu bar where we could link to "get started" page
